// <auto-generated />
namespace PhoneBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class group_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(group_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "201507141448050_group_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
